version: '3'
services:
  app:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=book_shelf_db
      - POSTGRES_USER=book_shelf_user
      - POSTGRES_PASSWORD=book_shelf_pass
    ports:
      - "5480:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U book_shelf_user -d book_shelf_db"]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always