version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=book_shelf_db
      - POSTGRES_USER=book_shelf_user
      - POSTGRES_PASSWORD=book_shelf_pass
    ports:
      - "5480:5432"
    restart: always